<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>oxebots_observers</name>
  <version>0.0.0</version>
  <description>This package is part of the OxeBots SSL RoboCup league, designed to interface with
    the communication system to extract and interpret game object states in real-time.</description>
  <maintainer email="ce.cesc01@gmail.com">carlos</maintainer>
  <license>GPLv3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>oxebots_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>